DROP TABLE IF EXISTS HOUSEHOLD;

CREATE TABLE HOUSEHOLD(
SERIALNUMBER SERIAL PRIMARY KEY NOT NULL,
BRAND VARCHAR(30) NOT NULL,
MODEL VARCHAR(30) NOT NULL,
STATUS VARCHAR(30) NOT NULL,
DATE DATE
);

INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATE) VALUES('samsung','s100','active','2022-11-11');
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATE) VALUES('samsung','s200','active','2022-11-12');
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATE) VALUES('LG','L100','inactive','2022-11-13');
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATE) VALUES('Hitachi','H100','active','2022-11-14');
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATE) VALUES('Sony','SS100','active','2022-11-16');
INSERT INTO HOUSEHOLD(BRAND,MODEL,STATUS,DATE) VALUES('OGeneral','0100','active','2022-11-17');